spring.datasource.url=jdbc:postgresql://localhost:5432/semester_project_db
spring.datasource.username=postgres
spring.datasource.password=8848abcd
spring.jpa.hibernate.ddl-auto=update
# JWT
app.jwt.secret=semesterProjectSecretKeyForJwtTokenGeneration123456789
app.jwt.expiration-ms=86400000
# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=smoke.paladin@gmail.com
spring.mail.password=omqtjbkotmkokjne
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.mail.from=smoke.paladin@gmail.com